version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:$ENVIRONMENT
  post_build:
    commands:
      - aws s3 sync ./build $S3_BUCKET 
